# Generated by Django 2.2.12 on 2023-04-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u', '0002_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='designation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
